apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "API_testing"
  description: "api for testing"
  annotations:
    backstage.io/targetusers: Internal
    backstage.io/targetusers: public
spec:
  type: openapi
  owner: user:SreeHarshithaGaddam
  lifecycle: experimental
  definition: "sample definition"
